development:
  adapter: postgresql
  database: captest_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: captest_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: captest
  username: vagrant
  password: vagrant
  pool: 5
  timeout: 5000
